//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportShow
    {
        public int ImportShowID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Name { get; set; }
        public System.DateTime ShowDate { get; set; }
        public string ShowVendorRef { get; set; }
        public string VenueName { get; set; }
        public Nullable<int> GFVenueID { get; set; }
        public string VenueVendorID { get; set; }
        public string VenueTown { get; set; }
        public string VenuePostcode { get; set; }
        public string VenueLat { get; set; }
        public string VenueLong { get; set; }
        public Nullable<int> GFArtistID { get; set; }
        public string ArtistName { get; set; }
    }
}
