//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Threading;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using GigsFirstBLL.Properties;

#pragma warning disable 1591

namespace GigsFirstBLL.com.productserve.ticketmaster {
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.0.30319.33440")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="ServiceBinding", Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    [SoapInclude(typeof(Category))]
    [SoapInclude(typeof(ParentCategory))]
    [SoapInclude(typeof(Artist))]
    [SoapInclude(typeof(Event))]
    [SoapInclude(typeof(FindEventsRequest_Filter))]
    public partial class ServiceService : SoapHttpClientProtocol {
        
        private SendOrPostCallback findEventsOperationCompleted;
        
        private SendOrPostCallback getCategoriesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceService() {
            this.Url = Settings.Default.GigsFirstBLL_com_productserve_ticketmaster_ServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event findEventsCompletedEventHandler findEventsCompleted;
        
        /// <remarks/>
        public event getCategoriesCompletedEventHandler getCategoriesCompleted;
        
        /// <remarks/>
        [SoapRpcMethod("http://ticketmaster.productserve.com/v3/soap.php#findEvents", RequestNamespace="http://ticketmaster.productserve.com/v3/soap.php", ResponseNamespace="http://ticketmaster.productserve.com/v3/soap.php")]
        [return: SoapElement("return")]
        public FindEventsResponse findEvents(FindEventsRequest request) {
            object[] results = this.Invoke("findEvents", new object[] {
                        request});
            return ((FindEventsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void findEventsAsync(FindEventsRequest request) {
            this.findEventsAsync(request, null);
        }
        
        /// <remarks/>
        public void findEventsAsync(FindEventsRequest request, object userState) {
            if ((this.findEventsOperationCompleted == null)) {
                this.findEventsOperationCompleted = new SendOrPostCallback(this.OnfindEventsOperationCompleted);
            }
            this.InvokeAsync("findEvents", new object[] {
                        request}, this.findEventsOperationCompleted, userState);
        }
        
        private void OnfindEventsOperationCompleted(object arg) {
            if ((this.findEventsCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.findEventsCompleted(this, new findEventsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [SoapRpcMethod("http://ticketmaster.productserve.com/v3/soap.php#getCategories", RequestNamespace="http://ticketmaster.productserve.com/v3/soap.php", ResponseNamespace="http://ticketmaster.productserve.com/v3/soap.php")]
        [return: SoapElement("return")]
        public GetCategoriesResponse getCategories(GetCategoriesRequest request) {
            object[] results = this.Invoke("getCategories", new object[] {
                        request});
            return ((GetCategoriesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void getCategoriesAsync(GetCategoriesRequest request) {
            this.getCategoriesAsync(request, null);
        }
        
        /// <remarks/>
        public void getCategoriesAsync(GetCategoriesRequest request, object userState) {
            if ((this.getCategoriesOperationCompleted == null)) {
                this.getCategoriesOperationCompleted = new SendOrPostCallback(this.OngetCategoriesOperationCompleted);
            }
            this.InvokeAsync("getCategories", new object[] {
                        request}, this.getCategoriesOperationCompleted, userState);
        }
        
        private void OngetCategoriesOperationCompleted(object arg) {
            if ((this.getCategoriesCompleted != null)) {
                InvokeCompletedEventArgs invokeArgs = ((InvokeCompletedEventArgs)(arg));
                this.getCategoriesCompleted(this, new getCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            Uri wsUri = new Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class FindEventsRequest {
        
        private Nullable<int> resultsPerPageField;
        
        private Nullable<int> currentPageField;
        
        private FindEventsRequest_Sort sortField;
        
        private FindEventsRequest_Filter[] filtersField;
        
        private string updatedSinceField;
        
        private string apiKeyField;
        
        private string countryField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> resultsPerPage {
            get {
                return this.resultsPerPageField;
            }
            set {
                this.resultsPerPageField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public FindEventsRequest_Sort sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public FindEventsRequest_Filter[] filters {
            get {
                return this.filtersField;
            }
            set {
                this.filtersField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string updatedSince {
            get {
                return this.updatedSinceField;
            }
            set {
                this.updatedSinceField = value;
            }
        }
        
        /// <remarks/>
        public string apiKey {
            get {
                return this.apiKeyField;
            }
            set {
                this.apiKeyField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class FindEventsRequest_Sort {
        
        private string fieldField;
        
        private string orderField;
        
        /// <remarks/>
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class Category {
        
        private string nameField;
        
        private Nullable<int> categoryIdField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class ParentCategory {
        
        private string nameField;
        
        private Nullable<int> categoryIdField;
        
        private Category[] categoriesField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Category[] categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class GetCategoriesResponse {
        
        private ParentCategory[] parentCategoryField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public ParentCategory[] parentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class GetCategoriesRequest {
        
        private string apiKeyField;
        
        private string countryField;
        
        /// <remarks/>
        public string apiKey {
            get {
                return this.apiKeyField;
            }
            set {
                this.apiKeyField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class Venue {
        
        private Nullable<int> venueIdField;
        
        private Nullable<int> ticketmasterVenueIdField;
        
        private string nameField;
        
        private string streetField;
        
        private string cityField;
        
        private string countryField;
        
        private string postcodeField;
        
        private string urlField;
        
        private string imageUrlField;
        
        private string stateField;
        
        private Nullable<float> longitudeField;
        
        private Nullable<float> latitudeField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> venueId {
            get {
                return this.venueIdField;
            }
            set {
                this.venueIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> ticketmasterVenueId {
            get {
                return this.ticketmasterVenueIdField;
            }
            set {
                this.ticketmasterVenueIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<float> longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<float> latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class Artist {
        
        private Nullable<int> artistIdField;
        
        private Nullable<int> ticketmasterArtistIdField;
        
        private string nameField;
        
        private string urlField;
        
        private string imageUrlField;
        
        private string categoryField;
        
        private Nullable<int> categoryIdField;
        
        private string parentCategoryField;
        
        private Nullable<int> parentCategoryIdField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> artistId {
            get {
                return this.artistIdField;
            }
            set {
                this.artistIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> ticketmasterArtistId {
            get {
                return this.ticketmasterArtistIdField;
            }
            set {
                this.ticketmasterArtistIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string imageUrl {
            get {
                return this.imageUrlField;
            }
            set {
                this.imageUrlField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string parentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> parentCategoryId {
            get {
                return this.parentCategoryIdField;
            }
            set {
                this.parentCategoryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class Event {
        
        private Nullable<int> eventIdField;
        
        private string ticketmasterEventIdField;
        
        private string statusField;
        
        private string nameField;
        
        private string urlField;
        
        private string eventDateField;
        
        private string onSaleDateField;
        
        private string preSaleDateField;
        
        private string categoryField;
        
        private Nullable<int> categoryIdField;
        
        private string parentCategoryField;
        
        private Nullable<int> parentCategoryIdField;
        
        private Nullable<float> minPriceField;
        
        private Nullable<float> maxPriceField;
        
        private string currencyField;
        
        private string descriptionField;
        
        private Artist[] artistsField;
        
        private Venue venueField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> eventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string ticketmasterEventId {
            get {
                return this.ticketmasterEventIdField;
            }
            set {
                this.ticketmasterEventIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string onSaleDate {
            get {
                return this.onSaleDateField;
            }
            set {
                this.onSaleDateField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string preSaleDate {
            get {
                return this.preSaleDateField;
            }
            set {
                this.preSaleDateField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> categoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string parentCategory {
            get {
                return this.parentCategoryField;
            }
            set {
                this.parentCategoryField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> parentCategoryId {
            get {
                return this.parentCategoryIdField;
            }
            set {
                this.parentCategoryIdField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<float> minPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<float> maxPrice {
            get {
                return this.maxPriceField;
            }
            set {
                this.maxPriceField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Artist[] artists {
            get {
                return this.artistsField;
            }
            set {
                this.artistsField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Venue venue {
            get {
                return this.venueField;
            }
            set {
                this.venueField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class Details {
        
        private Nullable<int> totalResultsField;
        
        private Nullable<int> totalPagesField;
        
        private Nullable<int> currentPageField;
        
        private Nullable<int> resultsPerPageField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> totalResults {
            get {
                return this.totalResultsField;
            }
            set {
                this.totalResultsField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> totalPages {
            get {
                return this.totalPagesField;
            }
            set {
                this.totalPagesField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> currentPage {
            get {
                return this.currentPageField;
            }
            set {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Nullable<int> resultsPerPage {
            get {
                return this.resultsPerPageField;
            }
            set {
                this.resultsPerPageField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class FindEventsResponse {
        
        private Details detailsField;
        
        private Event[] resultsField;
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Details details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [SoapElement(IsNullable=true)]
        public Event[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Xml", "4.0.30319.34230")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [SoapType(Namespace="http://ticketmaster.productserve.com/v3/soap.php")]
    public partial class FindEventsRequest_Filter {
        
        private string objectField;
        
        private string fieldField;
        
        private object[] valuesField;
        
        /// <remarks/>
        public string @object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public object[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.0.30319.33440")]
    public delegate void findEventsCompletedEventHandler(object sender, findEventsCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.0.30319.33440")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class findEventsCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findEventsCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FindEventsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FindEventsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.0.30319.33440")]
    public delegate void getCategoriesCompletedEventHandler(object sender, getCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [GeneratedCode("System.Web.Services", "4.0.30319.33440")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class getCategoriesCompletedEventArgs : AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCategoriesCompletedEventArgs(object[] results, Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetCategoriesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetCategoriesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591