//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GigsFirstEntities : DbContext
    {
        public GigsFirstEntities()
            : base("name=GigsFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ArtistAlias> ArtistAliases { get; set; }
        public DbSet<Artist> Artists { get; set; }
        public DbSet<AttendanceType> AttendanceTypes { get; set; }
        public DbSet<ImportShow> ImportShows { get; set; }
        public DbSet<ShowArtist> ShowArtists { get; set; }
        public DbSet<ShowCategory> ShowCategories { get; set; }
        public DbSet<Show> Shows { get; set; }
        public DbSet<ShowStatus> ShowStatuses { get; set; }
        public DbSet<ShowVendor> ShowVendors { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserShow> UserShows { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<VenueAlias> VenueAliases { get; set; }
        public DbSet<Venue> Venues { get; set; }
    }
}
