//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowVendor
    {
        public int ShowVendorID { get; set; }
        public int VendorID { get; set; }
        public int ShowID { get; set; }
        public string VendorRefCode { get; set; }
        public string Price { get; set; }
        public string Status { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
    
        public virtual Show Show { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
