//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public Show()
        {
            this.ShowArtists = new HashSet<ShowArtist>();
            this.ShowVendors = new HashSet<ShowVendor>();
            this.UserShows = new HashSet<UserShow>();
        }
    
        public int ShowID { get; set; }
        public int VenueID { get; set; }
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public System.DateTime ShowDate { get; set; }
        public string ShowTime { get; set; }
        public int StatusID { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
    
        public virtual ICollection<ShowArtist> ShowArtists { get; set; }
        public virtual ShowCategory ShowCategory { get; set; }
        public virtual ShowStatus ShowStatus { get; set; }
        public virtual Venue Venue { get; set; }
        public virtual ICollection<ShowVendor> ShowVendors { get; set; }
        public virtual ICollection<UserShow> UserShows { get; set; }
    }
}
