//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShow
    {
        public int UserShowID { get; set; }
        public int UserID { get; set; }
        public int ShowID { get; set; }
        public int AttendanceTypeID { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual Show Show { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
