//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigsFirstDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueAlias
    {
        public int VenueAliasID { get; set; }
        public int VenueID { get; set; }
        public string Name { get; set; }
        public string Town { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
